# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookInfo(object):
    def setupUi(self, BookInfo):
        BookInfo.setObjectName("BookInfo")
        BookInfo.resize(722, 524)
        self.tableView = QtWidgets.QTableView(BookInfo)
        self.tableView.setGeometry(QtCore.QRect(55, 150, 611, 271))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(BookInfo)
        self.lineEdit.setGeometry(QtCore.QRect(202, 35, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(BookInfo)
        self.label.setGeometry(QtCore.QRect(60, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(BookInfo)
        self.pushButton.setGeometry(QtCore.QRect(550, 36, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(BookInfo)
        self.label_2.setGeometry(QtCore.QRect(60, 73, 161, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(BookInfo)
        self.label_3.setGeometry(QtCore.QRect(61, 114, 131, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(BookInfo)
        self.pushButton_2.setGeometry(QtCore.QRect(571, 460, 101, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(BookInfo)
        self.pushButton.clicked.connect(BookInfo.searchButton_Click)
        self.pushButton_2.clicked.connect(BookInfo.backButton_Click)
        QtCore.QMetaObject.connectSlotsByName(BookInfo)

    def retranslateUi(self, BookInfo):
        _translate = QtCore.QCoreApplication.translate
        BookInfo.setWindowTitle(_translate("BookInfo", "BookInfo"))
        self.label.setText(_translate("BookInfo", "请输入书号："))
        self.pushButton.setText(_translate("BookInfo", "搜索"))
        self.label_2.setText(_translate("BookInfo", "书名："))
        self.label_3.setText(_translate("BookInfo", "借阅记录："))
        self.pushButton_2.setText(_translate("BookInfo", "返回"))
