# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Confirm(object):
    def setupUi(self, Confirm):
        Confirm.setObjectName("Confirm")
        Confirm.resize(600, 250)
        self.label = QtWidgets.QLabel(Confirm)
        self.label.setGeometry(QtCore.QRect(180, 50, 251, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Confirm)
        self.pushButton.setGeometry(QtCore.QRect(131, 127, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Confirm)
        self.pushButton_2.setGeometry(QtCore.QRect(341, 127, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Confirm)
        self.pushButton.clicked.connect(Confirm.yesButton_Click)
        self.pushButton_2.clicked.connect(Confirm.noButton_Click)
        QtCore.QMetaObject.connectSlotsByName(Confirm)

    def retranslateUi(self, Confirm):
        _translate = QtCore.QCoreApplication.translate
        Confirm.setWindowTitle(_translate("Confirm", "Confirm"))
        self.label.setText(_translate("Confirm", "确认借/还书？"))
        self.pushButton.setText(_translate("Confirm", "是"))
        self.pushButton_2.setText(_translate("Confirm", "否"))
