# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Password(object):
    def setupUi(self, Password):
        Password.setObjectName("Password")
        Password.resize(500, 250)
        self.label_2 = QtWidgets.QLabel(Password)
        self.label_2.setGeometry(QtCore.QRect(121, 165, 271, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Password)
        self.label.setGeometry(QtCore.QRect(121, 63, 271, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Password)
        self.layoutWidget.setGeometry(QtCore.QRect(121, 128, 271, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(Password)
        self.lineEdit.setGeometry(QtCore.QRect(121, 98, 271, 23))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Password)
        self.pushButton.clicked.connect(Password.yesButton_Click)
        self.pushButton_2.clicked.connect(Password.noButton_Click)
        QtCore.QMetaObject.connectSlotsByName(Password)

    def retranslateUi(self, Password):
        _translate = QtCore.QCoreApplication.translate
        Password.setWindowTitle(_translate("Password", "Form"))
        self.label_2.setText(_translate("Password", "TextLabel"))
        self.label.setText(_translate("Password", "请输入密码"))
        self.pushButton.setText(_translate("Password", "确认"))
        self.pushButton_2.setText(_translate("Password", "取消"))
