# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentSearch(object):
    def setupUi(self, StudentSearch):
        StudentSearch.setObjectName("StudentSearch")
        StudentSearch.resize(732, 523)
        self.label = QtWidgets.QLabel(StudentSearch)
        self.label.setGeometry(QtCore.QRect(75, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(StudentSearch)
        self.lineEdit.setGeometry(QtCore.QRect(199, 52, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(StudentSearch)
        self.pushButton.setGeometry(QtCore.QRect(530, 54, 92, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(StudentSearch)
        self.tableView.setGeometry(QtCore.QRect(70, 150, 601, 281))
        self.tableView.setObjectName("tableView")
        self.label_2 = QtWidgets.QLabel(StudentSearch)
        self.label_2.setGeometry(QtCore.QRect(75, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(StudentSearch)
        self.label_3.setGeometry(QtCore.QRect(76, 89, 151, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(StudentSearch)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 460, 92, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(StudentSearch)
        self.pushButton.clicked.connect(StudentSearch.searchButton_Click)
        self.pushButton_2.clicked.connect(StudentSearch.backButton_Click)
        QtCore.QMetaObject.connectSlotsByName(StudentSearch)

    def retranslateUi(self, StudentSearch):
        _translate = QtCore.QCoreApplication.translate
        StudentSearch.setWindowTitle(_translate("StudentSearch", "StudentSearch"))
        self.label.setText(_translate("StudentSearch", "请输入学号："))
        self.pushButton.setText(_translate("StudentSearch", "搜索"))
        self.label_2.setText(_translate("StudentSearch", "借阅记录："))
        self.label_3.setText(_translate("StudentSearch", "姓名："))
        self.pushButton_2.setText(_translate("StudentSearch", "返回"))
