# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(734, 504)
        self.pushButton = QtWidgets.QPushButton(Welcome)
        self.pushButton.setGeometry(QtCore.QRect(600, 440, 92, 28))
        self.pushButton.setObjectName("pushButton")
        self.splitter = QtWidgets.QSplitter(Welcome)
        self.splitter.setGeometry(QtCore.QRect(220, 170, 260, 121))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Welcome)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 310, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Welcome)
        self.label_3.setGeometry(QtCore.QRect(240, 380, 221, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Welcome)
        self.pushButton.clicked.connect(Welcome.adminButton_Click)
        self.pushButton_2.clicked.connect(Welcome.start_student)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Form"))
        self.pushButton.setText(_translate("Welcome", "管理员"))
        self.label.setText(_translate("Welcome", "欢迎使用图书管理系统"))
        self.label_2.setText(_translate("Welcome", "请刷卡"))
        self.pushButton_2.setText(_translate("Welcome", "刷卡登录"))
        self.label_3.setText(_translate("Welcome", "TextLabel"))
